version: "3.9" 

volumes:
  v18s1_server_data:
    external: 
      name:  ${V18S1_VOLUME_SERVER_DATA}

services:

  server:
    build:
      context: .
      args:
        sshrootpassword: ${SSH_ROOT_PASSWORD}
    ports:
      - ${PAPER_PORT}:25565
      - ${SSH_PORT}:22

    volumes:
#      - .:/mc
      - v18s1_server_data:/mc/

    restart: always


    stdin_open: true #docker run -i
    tty: true        #docker run -t

    stop_grace_period: 1m30s

    environment:
      MEMORYSIZE: "1G"


    networks:
      mc-server-net:
        ipv4_address: 172.16.226.3


networks:
  mc-server-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.226.0/24"
          gateway: 172.16.226.1
        - subnet: "2001:3984:3926::/64"
